apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: complete-production-e2e-pipeline
  labels:
    app: complete-production-e2e-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-production-e2e-pipeline
  template:
    metadata:
      labels:
        app: complete-production-e2e-pipeline
    spec:
      containers:
      - name: complete-production-e2e-pipeline
        image: kipkulei/complete-production-e2e-pipeline:1.0.0-10
        ports:
        - containerPort: 8080
