apiVersion: v1
kind: service
metadata:
  namespace: default
  creationTimestamp: null
  labels:
    app: test
  name: complete-production-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test
  type: ClusterIP
status:
  loadBalancer: {}
